name: Auto commit

on:
  push:
    branches:
      - master

  schedule:
    - cron: "1 * * * *" # 每小时执行一次

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG
        run: echo "::debug::Ref = ${{github.ref}}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update
        run: |
          d=$(date '+%Y-%m-%dT%H:%M:%SZ')
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "ruansiyi233@gmail.com"
          git config --local user.name "ShengyiRuan"
          git add LAST_UPDATED

          arr[0]="chore(bot): 😂 auto commit"
          arr[1]="chore(bot): 😱 auto commit"
          arr[2]="chore(bot): 👿 auto commit"
          arr[3]="chore(bot): 💩 auto commit"
          arr[4]="chore(bot): 🙏 auto commit"
          arr[5]="chore(bot): 🙈 auto commit"
          arr[6]="chore(bot): 🐐 auto commit"
          arr[7]="chore(bot): 🤖 auto commit"
          arr[8]="chore(bot): 🟩 auto commit"
          arr[9]="chore(bot): 👻 auto commit"

          rand=$((RANDOM % ${#arr[@]}))

          git commit -m "${arr[$rand]}"

      - name: GitHub Push
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          push-branch: master
          commit-message: "Auto commit"
